version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      next-ecosystem:
        patterns:
          - "next*"
          - "eslint-config-next"
          - "react*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]